ip_forward: true
network_compression_threshold: 256
stats: fc502c80-c38d-402f-b8c3-0ca541147aa6
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - multichat.chat.mode
  - multichat.chat.msg
  - multichat.group
  - multichat.group.create
  - multichat.chat.helpme
  - multichat.chat.clear
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - multichat.staff.spy.bypass
  - multichat.staff.admin
  - multichat.*
  - multiaccountfinder.admin
  - bungeecord.command.send
  - cdispatch.*
  - bungeemotd.reload
  - bungeemotd.set
  - multichat.staff.list
  - multichat.staff.listgroups
  - multichat.staff.mod
  - multichat.staff.spy
  - multichat.staff.display
  - multichat.chat.color
  - multichat.chat.freeze
  - multichat.chat.always
  - multichat.chat.clear.all
  - multichat.chat.clear.global
  - multichat.chat.clear.server
  - multichat.announce
  - multichat.bulletin
  - multichat.cast.
  - multichat.cast.admin
  - multichat.staff.admin
  - multichat.admin
  - multichat.staff.spy.bypass
  - bungeeperms.help
  - bungeeperms.reload
  - bungeeperms.users
  - bungeeperms.user.info
  - bungeeperms.user.delete
  - bungeeperms.user.perms.add
  - bungeeperms.user.perms.remove
  - bungeeperms.user.perms.has
  - bungeeperms.user.perms.list
  - bungeeperms.user.group.add
  - bungeeperms.user.group.remove
  - bungeeperms.user.group.set
  - bungeeperms.user.groups
  - bungeeperms.groups
  - bungeeperms.groups.info
  - bungeeperms.groups.create
  - bungeeperms.groups.delete
  - bungeeperms.group.inheritances.add
  - bungeeperms.group.inheritances.remove
  - bungeeperms.group.rank
  - bungeeperms.group.default
  - bungeeperms.group.display
  - bungeeperms.group.prefix
  - bungeeperms.group.suffix
  - bungeeperms.group.perms.add
  - bungeeperms.group.perms.remove
  - bungeeperms.group.perms.has
  - bungeeperms.group.perms.list
  - bungeeperms.promote
  - bungeeperms.demote
  - bungeeperms.cleanup
  - bungeeperms.format
  - bungeeperms.backend
  - bungeeperms.migrate
  - bungeeperms.uuid
  staff_full_access:
  - multichat.staff.list
  - multichat.staff.listgroups
  - multichat.staff.mod
  - multichat.staff.spy
  - multichat.staff.display
  - multichat.chat.color
  - multichat.chat.freeze
  - multichat.chat.always
  - multichat.chat.clear.all
  - multichat.chat.clear.global
  - multichat.chat.clear.server
  - multichat.announce
  - multichat.bulletin
  - multichat.cast.
  - multichat.cast.admin
  staff:
  - multichat.staff.list
  - multichat.staff.listgroups
  - multichat.staff.mod
  - multichat.staff.spy
  - multichat.staff.display
  - multichat.chat.color
  - multichat.chat.freeze
  - multichat.chat.always
groups:
  Bradisswag:
  - admin
  - staff
  Etanarvazac:
  - admin
  - staff
  Fred_o_PAIN:
  - admin
  - staff
servers:
  Hub:
    motd: '&1Welcome to Trafourmium Hub!'
    address: localhost:25566
    restricted: false
  Survival:
    motd: '&1Welcome to Trafourmium Survival!'
    address: localhost:25567
    restricted: false
  PS:
    motd: '&lWelcome to Trafourmium Private Survival'
    address: localhost:25568
    restricted: true
  Bowplinko:
    motd: '&lWelcome to Trafourmium Bowplinko'
    address: localhost:25569
    restricted: false
  BlastOff:
    motd: '&lWelcome to Trafourmium Blast Off'
    address: localhost:25570
    restricted: false
  Temp-test-server:
    motd: '&1Welcome to Trafourmium test'
    address: localhost:25571
    restricted: false
  Murder:
    motd: '&1Welcome to Trafourmium Murder'
    address: localhost:25572
    restricted: false
  Minigames:
    motd: '&1Welcome to Trafourmium Minigames!'
    address: localhost:25573
    restricted: false
  Factions:
    motd: '&1Welcome to Trafourmium Factions!'
    address: localhost:25574
    restricted: false
timeout: 30000
listeners:
- query_port: 25563
  motd: '&a[&bTrafourmiumNetwork&a][&c1.9+ - 1.12.2&8]'
  priorities:
  - Hub
  - Survival
  - PS
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    TrafourmiumNetwork.serveminecraft.net: Survival
  max_players: 500
  tab_size: 200
  ping_passthrough: false
  force_default_server: true
  proxy_protocol: false
prevent_proxy_connections: false
player_limit: 0
online_mode: true
log_commands: false
disabled_commands:
- plugin
- plugins
- pl
connection_throttle: 4000
